//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_De_Vendas.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public string nome_usuario { get; set; }
        public string senha { get; set; }
    }
}
